[project]
name = "renderrob"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bpy",
    "setuptools",
    "py2app>=0.28.8",
    "protobuf>=6.33.0",
    "py2appsigner>=0.6.95",
    "pyside6-essentials>=6.10.0",
]
